### ISSUE TITLE
Wrong path in compose file

### ISSUE THREAD

**Issue by WhileDekker** [stepman0/docker-sonos-kids-controller#28]
HI

@stepman0 : thx for creating the docker!!

I just found one minor thing:
the settings.json is loaded from /app/settings.json, therefore the path in the compose file (your example) should be

      - ./api/settings.json:/app/settings.json

Its correctly described here: https://github.com/chrisns/docker-node-sonos-http-api but apparently also wrong here: https://hub.docker.com/r/chrisns/docker-node-sonos-http-api

**Comment by stepman0** [comment]
Just fixed - thanks.
